### ISSUE TITLE
Make earmark and ex_doc dev or docs only dependencies

### ISSUE THREAD

**Issue by ericmj** [OnorioCatenacci/pragmatic#1]
It seems like they are not used in production so they should not be added as dependencies to the Hex package.

Thanks for this library! :heart:

**Comment by OnorioCatenacci** [comment]
Hi Eric,

You're right.  I just need to retool to call ex_doc from the command line.
Thanks for the reminder!

And thank _you_ for making it so very easy to share a new library with
other alchemists!

## 

Onorio

On Wed, Mar 23, 2016 at 11:27 AM, Eric Meadows-Jönsson <
notifications@github.com> wrote:

> It seems like they are not used in production so they should not be added
> as dependencies to the Hex package.
> 
> Thanks for this library! [image: :heart:]
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/OnorioCatenacci/pragmatic/issues/1

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci
